version: '3.8'
services:
  server:
    restart: always
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - ./bots.json:/server/bots.json
      - ./config.json:/server/config.json
      # - ./blocked.txt:/server/blocked.txt
      # - /etc/letsencrypt/live/YOUR-DOMAIN.COM/fullchain.pem:/cert/webhook_cert.pem
      # - /etc/letsencrypt/live/YOUR-DOMAIN.COM/privkey.pem:/cert/webhook_pkey.pem
      # - ./id_garden:/server/id_garden
    build: server
    container_name: bots_server_telegram
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"