version: '3.8'
services:
  server:
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./bots.json:/server/bots.json
      - ./config.json:/server/config.json
    build: server
    container_name: telegram_bot_server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow