version: '3.8'
services:
  server:
    # restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./bots.json:/server/bots.json
      - ./config.json:/server/config.json
      - ./blocked.txt:/server/blocked.txt
      - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/cert/webhook_cert.pem
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/cert/webhook_pkey.pem
    build: server
    container_name: bots_server_telegram
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow